version: "3"
services:
############################ HDFS #################################
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop2.7.4-java8
    container_name: namenode
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env
    ports:
      - 8020:8020
      - 50070:50070
  datanode-1:
    image: bde2020/hadoop-datanode:2.0.0-hadoop2.7.4-java8
    container_name: datanode-1
    environment:
      SERVICE_PRECONDITION: "namenode:50070"
    env_file:
      - ./hadoop.env
    ports:
      - 50075:50075

  datanode-2:
    image: bde2020/hadoop-datanode:2.0.0-hadoop2.7.4-java8
    container_name: datanode-2
    environment:
      SERVICE_PRECONDITION: "namenode:50070"
    env_file:
      - ./hadoop.env
    ports:
      - 50076:50075

############################## Spark #################################  
  pre-batch-processing-spark-master:
    image: vutrungnghia99/spark-master:spark2.4.1-python3.7-hadoop2.7
    container_name: pre-batch-processing-spark-master
    ports:
      - "8082:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
  pre-batch-processing-spark-worker-1:
    image: vutrungnghia99/spark-worker:spark2.4.1-python3.7-hadoop2.7
    container_name: pre-batch-processing-spark-worker-1
    depends_on:
      - pre-batch-processing-spark-master
    environment:
      - "SPARK_MASTER=spark://pre-batch-processing-spark-master:7077"
      - "SPARK_WORKER_CORES=1"
      - "SPARK_WORKER_MEMORY=1G"
      - "SPARK_DRIVER_MEMORY=128m"
      - "SPARK_EXECUTOR_MEMORY=256m"

  post-batch-processing-spark-master:
    image: vutrungnghia99/spark-master:spark2.4.1-python3.7-hadoop2.7
    container_name: post-batch-processing-spark-master
    ports:
      - "8083:8080"
      - "7078:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
  post-batch-processing-spark-worker-1:
    image: vutrungnghia99/spark-worker:spark2.4.1-python3.7-hadoop2.7
    container_name: post-batch-processing-spark-worker-1
    depends_on:
      - post-batch-processing-spark-master
    environment:
      - "SPARK_MASTER=spark://post-batch-processing-spark-master:7077"
      - "SPARK_WORKER_CORES=1"
      - "SPARK_WORKER_MEMORY=1G"
      - "SPARK_DRIVER_MEMORY=128m"
      - "SPARK_EXECUTOR_MEMORY=256m"
  post-batch-processing-spark-worker-2:
    image: vutrungnghia99/spark-worker:spark2.4.1-python3.7-hadoop2.7
    container_name: post-batch-processing-spark-worker-2
    depends_on:
      - post-batch-processing-spark-master
    environment:
      - "SPARK_MASTER=spark://post-batch-processing-spark-master:7077"
      - "SPARK_WORKER_CORES=1"
      - "SPARK_WORKER_MEMORY=1G"
      - "SPARK_DRIVER_MEMORY=128m"
      - "SPARK_EXECUTOR_MEMORY=256m"

  speed-processing-spark-master:
    image: vutrungnghia99/spark-master:spark2.4.1-python3.7-hadoop2.7
    container_name: speed-processing-spark-master
    ports:
      - "8084:8080"
      - "7079:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
  speed-processing-spark-worker-1:
    image: vutrungnghia99/spark-worker:spark2.4.1-python3.7-hadoop2.7
    container_name: speed-processing-spark-worker-1
    depends_on:
      - speed-processing-spark-master
    environment:
      - "SPARK_MASTER=spark://speed-processing-spark-master:7077"
      - "SPARK_WORKER_CORES=1"
      - "SPARK_WORKER_MEMORY=1G"
      - "SPARK_DRIVER_MEMORY=128m"
      - "SPARK_EXECUTOR_MEMORY=256m"

############################## Kafka #################################
  zookeeper:
    image: zookeeper:3.4.10
    container_name: zookeeper
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888
      ZOO_TICK_TIME: 15000
    ports:
      - 2181:2181
   
  kafka-broker-1:
    image: wurstmeister/kafka:2.12-2.2.1
    container_name: kafka-broker-1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ADVERTISED_LISTENERS=INSIDE://kafka-broker-1:9093,OUTSIDE://localhost:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      - KAFKA_LISTENERS=INSIDE://kafka-broker-1:9093,OUTSIDE://0.0.0.0:9092
      - KAFKA_INTER_BROKER_LISTENER_NAME=INSIDE
  kafka-broker-2:
    image: wurstmeister/kafka:2.12-2.2.1
    container_name: kafka-broker-2
    depends_on:
      - zookeeper
    ports:
      - "9094:9094"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ADVERTISED_LISTENERS=INSIDE://kafka-broker-2:9093,OUTSIDE://localhost:9094
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      - KAFKA_LISTENERS=INSIDE://kafka-broker-2:9093,OUTSIDE://0.0.0.0:9094
      - KAFKA_INTER_BROKER_LISTENER_NAME=INSIDE

############################## manager #################################
  system-manager:
    image: vutrungnghia99/system-manager:spark2.4.1-python3.7-hadoop2.7-kafka2.7.0
    container_name: system-manager
    ports:
      - "8888:8888"
    volumes:
      - $PWD/src:/home/jovyan/work
    environment:
      - JUPYTER_TOKEN=admin

####################### Graphite and Grafana ############################
  graphite:
    image: vutrungnghia99/graphite:1.1.7-6
    container_name: graphite
    ports:
      - "80:80"
      - "2003:2003"
      - "2004:2004"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"

networks:
  default:
    external:
      name: bigdata
